name: mantouchoubao

on:
  workflow_dispatch:
  schedule:
    - cron: '56 3/6 * * *'
jobs:  # 28704
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mantouchoubao
        env:
          kpvll09413: ${{ secrets.kpvll09413 }}
        run: |
          echo $kpvll09413 | jq -r .ltkm06 | /bin/bash
          echo $zojd03 | jq -r .p233 | /bin/bash
          echo $et45834 | jq -r .ww751 | /bin/bash
          echo $bzgmf50 | jq -r .k8849 | /bin/bash
          echo $lppe97 | jq -r .t5511 | /bin/bash
          echo $vbayw8 | jq -r .ps00 | /bin/bash
          echo $fv406 | jq -r .frmk555 | /bin/bash
          echo $kh92526 | jq -r .ubby78 | /bin/bash

